### ISSUE TITLE
Can't find Python executable

### ISSUE THREAD

**Issue by pongsiri20907** [WorkAroundOnline/react-image-annotate#216]
I'm run "npm install react-image-annotate" and i found this error.
-------------------------------------------------------------------------
npm ERR! code 1
npm ERR! path C:\React\imageAnotation\label\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@4.0.0
npm ERR! gyp info using node@16.20.0 | win32 | x64
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "C:\Users\User\AppData\Local\Programs\Python\Python310\python.EXE", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\React\imageAnotation\label\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\React\imageAnotation\label\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\React\imageAnotation\label\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\React\\imageAnotation\\label\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\React\imageAnotation\label\node_modules\canvas
npm ERR! gyp ERR! node -v v16.20.0
npm ERR! gyp ERR! node-gyp -v v4.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2023-05-22T06_50_47_848Z-debug-0.log

**Comment by jpmancini** [comment]
Am also running into this issue. Looks like a duplicate though: https://github.com/UniversalDataTool/react-image-annotate/issues/183
